name: First Workflow
on: 
  pull_request:
   types:
     - opened
     - closed
   branches:
     - production:   
  Workflow_dispatch:   
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: printmeta data 
        run: echo "${{ toJSON(github)}}"
  