name: First Workflow
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: sleep 10s
  Deployment:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "second job"
      - name: Print goodbye
        run: echo "sechond good byee"      
